### ISSUE TITLE
Error in node_modules/axios/lib/core/createError.js:16 - Request failed with status code 401/303

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#257] opened 2021-03-15 21:29 UTC
## Error in Tree Mapper

**Error** in **node_modules/axios/lib/core/createError.js:16**
Request failed with status code 401/303

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=604fd1cf0073cb613b1d0000&i=gh&m=ci)

## Stacktrace

    node_modules/axios/lib/core/createError.js:16 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=604fd1cf0073cb613b1d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment] 2021-04-09 08:42
An error linked to this issue has been reopened in Bugsnag
[**Error** in **node_modules/axios/lib/core/createError.js:16**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=607013560077571b21a10000&i=gh&m=ra)

**Comment by norbertschuler** [comment] 2021-04-09 08:45
Testing the latest TestFlight version 1.0.1 on my iPhone X I got logged out while trying to upload the trees registered with version 1.0.0 before (after I upgraded the app) due to an 401 error (this is running against the production backend): 

https://user-images.githubusercontent.com/1532418/114153407-918e7380-991f-11eb-9c37-f252c097444b.mov

**Comment by norbertschuler** [comment] 2021-05-29 14:44
Bugsnag deleted the report, so we can not reproduce it anymore. Closing it. Maybe even resolved as we refactored the Auth0 usage.

**Comment by Plant-for-the-Planet** [comment] 2021-06-15 08:12
An error linked to this issue has been reopened in Bugsnag
[**Error** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=60c860fa007d077a02010000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment] 2021-07-28 14:33
An error linked to this issue has been reopened in Bugsnag
[**Error** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=61016abc007f8e3faef00000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment] 2021-12-01 01:54
An error linked to this issue has been reopened in Bugsnag
[**Error** in **node_modules/axios/lib/core/createError.js:16**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=61a6d5ef00896f27f1120000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment] 2022-01-31 11:16
An error linked to this issue has been reopened in Bugsnag
[**Error** in **node_modules/axios/lib/core/createError.js:16**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604fd1cf7352e400076a019b?event_id=61f7c4fc008d3c2d01ca0000&i=gh&m=ra)

**Closed** 2024-09-09 07:42 UTC
Labels: bug, bugsnag, production, 1.0.0
