### ISSUE TITLE
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#362] opened 2021-06-04 12:36 UTC
## Error in Tree Mapper

**java.lang.NullPointerException** in **MainActivity**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60ba1e375661d7000727fdc6?event_id=60ba1e37007d01ddda8d0000&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:883 - android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60ba1e375661d7000727fdc6?event_id=60ba1e37007d01ddda8d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-07-23 09:04
Duplicate of #383

**Closed by norbertschuler** 2021-07-23 09:04 UTC
Labels: 1.0.1, bug, bugsnag, production
