### ISSUE TITLE
Error in main.jsbundle:1343 - Some image upload are pending

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#296] opened 2021-04-09 07:15 UTC
## Error in Tree Mapper

**Error** in **main.jsbundle:1343**
Some image upload are pending

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/606ffef30b621b0007a41143?event_id=606ffef30077408d1b770001&i=gh&m=ci)

## Stacktrace

    main.jsbundle:1343 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/606ffef30b621b0007a41143?event_id=606ffef30077408d1b770001&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-04-09 08:43
Duplicate of #297

**Closed by norbertschuler** 2021-04-09 08:43 UTC
Labels: 1.0.1, bug, bugsnag, testflight
