### ISSUE TITLE
Error in app/repositories/maps.js:107

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#216] opened 2021-02-19 17:40 UTC
## Error in Tree Mapper

**Error** in **app/repositories/maps.js:107**
Attempting to create an object of type 'OfflineMaps' with an existing primary key value ''TreeMapper-offline-map-id-1613756438234''.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602ff81bbabf7600178d461e?event_id=602ff81b006cc3e4604e0000&i=gh&m=ci)

## Stacktrace

    app/repositories/maps.js:107 - 
    app/repositories/maps.js:106 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602ff81bbabf7600178d461e?event_id=602ff81b006cc3e4604e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-05-29 14:48
Duplicate of #308

**Closed by norbertschuler** 2021-05-29 14:48 UTC
Labels: 1.0.0, bug, bugsnag, testflight
