### ISSUE TITLE
TypeError in app/components/SelectCoordinates/index.js:332

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#250] opened 2021-03-10 09:32 UTC
## Error in Tree Mapper

**TypeError** in **app/components/SelectCoordinates/index.js:332**
null is not an object (evaluating 'J.inventory_id')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604892244303350008726af4?event_id=604892240072dea1b0c40000&i=gh&m=ci)

## Stacktrace

    app/components/SelectCoordinates/index.js:332 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/604892244303350008726af4?event_id=604892240072dea1b0c40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-05-29 14:42
Our codebase already changed a lot and this stracktrace is outdated, so cannot reproduce it anymore. Closing it.

**Closed by norbertschuler** 2021-05-29 14:42 UTC
Labels: 1.0.0, bug, bugsnag, testflight
