### ISSUE TITLE
Error in main.jsbundle:1095 - Request failed with status code 401

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#295] opened 2021-04-09 07:13 UTC
## Error in Tree Mapper

**Error** in **main.jsbundle:1095**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/606ffeb4a778850008f37d19?event_id=606ffeb4007735f51f720000&i=gh&m=ci)

## Stacktrace

    main.jsbundle:1095 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/606ffeb4a778850008f37d19?event_id=606ffeb4007735f51f720000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment] 2021-04-09 08:39
Testing the latest TestFlight version 1.0.1 on my iPhone X I got logged out while trying to upload the trees registered with version 1.0.0 before (after I upgraded the app) due to an 401 error (this is running against the production backend): 

https://user-images.githubusercontent.com/1532418/114153407-918e7380-991f-11eb-9c37-f252c097444b.mov

**Comment by norbertschuler** [comment] 2021-04-09 08:46
Duplicate of #257

**Closed by norbertschuler** 2021-04-09 08:46 UTC
Labels: 1.0.1, bug, bugsnag, testflight
